name: Weekly Security Scan

on:
  schedule:
    - cron: "16 0 * * 3"
  workflow_dispatch: {} # permite disparo manual para teste

jobs:
  scan:
    uses: kunumi/org-security/.github/workflows/secret-scan-reusable.yml@main
    with:
      scan_level: full
    secrets:
      KREPORTS_TOKEN: ${{ secrets.KREPORTS_TOKEN }}
